name: windzone
channels:
  - conda-forge
dependencies:
  - python=3.12
  - rasterio
  - richdem
  - whitebox
  - geopandas
  - xarray
  - netcdf4
  - cdsapi
  - scipy
  - pandas
  - jenkspy
  - pillow
  - matplotlib
